"""empty message

Revision ID: 172d7c2182d8
Revises: 4c67357db820
Create Date: 2021-07-08 18:03:19.062414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172d7c2182d8'
down_revision = '4c67357db820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
