"""empty message

Revision ID: 180550108a2b
Revises: 92e396fd40c4
Create Date: 2021-07-08 16:11:12.519007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180550108a2b'
down_revision = '92e396fd40c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('votes', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.drop_column('votes')

    # ### end Alembic commands ###
