"""empty message

Revision ID: 4c67357db820
Revises: da1bd6b7324a
Create Date: 2021-07-08 17:38:48.343051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c67357db820'
down_revision = 'da1bd6b7324a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_id', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.drop_column('unique_id')

    # ### end Alembic commands ###
